### ISSUE TITLE
Add new decidim's worldwide :)

### ISSUE THREAD

**Issue by xabier** [decidim/decidim.org#117]
I recently discovered these 4:

![image](https://user-images.githubusercontent.com/537284/37894768-9662e414-30df-11e8-9eaf-5feb1d4a0e6d.png)

* https://participation.lillemetropole.fr/

![image](https://user-images.githubusercontent.com/537284/37894794-adb5828e-30df-11e8-8a6f-95cee4f81bd1.png)

* http://burgos.decidimos.pt/

![image](https://user-images.githubusercontent.com/537284/37894879-ef16cbca-30df-11e8-9b00-b8ba3f0aff2b.png)

* https://dialogue-trianon.fr/

![image](https://user-images.githubusercontent.com/537284/37894904-00a3cabe-30e0-11e8-83fa-678bbb4d5bec.png)

* https://participate.oidp.net/

**Comment by xabier** [comment]
PR waiting for review at #118

**Comment by andreslucena** [comment]
Already added them
