### ISSUE TITLE
Link to social contract is wrong

### ISSUE THREAD

**Issue by PierreMesure** [decidim/decidim.org#161]
At this [line](https://github.com/decidim/decidim.org/blob/2c2ad51427bb47c63e17fab66e68b7774d60bfed/source/partials/values.html.erb#L30), the button saying "go to social contract" actually leads to the `/features` page... It should lead to `/contract`.

**Comment by andreslucena** [comment]
It's already fixed, closing this issue, thanks @PierreMesure
