### ISSUE TITLE
Bühl (Baden) is now using decidim

### ISSUE THREAD

**Issue by itrich** [decidim/decidim.org#210]
Dear community,

the German city [Bühl](https://goo.gl/maps/Z6tJ73eA814cPGpa6) is using decidim. In a first step, we will use decidim as internal collaboration/participatory plattform. After we adjusted the German translation and everything was tested successfully, we'll go public in a second step. Until then, you can link to our [Github repository](https://github.com/buehl/decidim-buehl-intra).

![logo_blue](https://user-images.githubusercontent.com/29982899/66369582-4ea3b680-e99d-11e9-8d1a-83bbbd3b1ff6.png)

[Logo_Stadt_Buehl.pdf](https://github.com/decidim/decidim.org/files/3700823/Logo_Stadt_Buehl.pdf)

Thank you for this great piece of software and publishing it free and open-source.

**Comment by andreslucena** [comment]
Hi @itrich 
Great news! Is the first german installation as far as I'm aware of. 
For publishing on decidim.org we'll wait until is on production, as we'd like to link to the production instance. Thanks for the notice and welcome to the community :D
