### ISSUE TITLE
translation missing: en.features.other.subtitle

### ISSUE THREAD

**Issue by PierreMesure** [decidim/decidim.org#244]
See on [this page](https://decidim.org/features/).

![image](https://user-images.githubusercontent.com/7223028/100475383-dfc27900-30da-11eb-9d5a-338c61b10955.png)

**Comment by andreslucena** [comment]
I've fixed it, thanks for the report!

**Comment by PierreMesure** [comment]
Great! Have a look at the PR's second commit, I added another fix for a missing translation!
