### ISSUE TITLE
I18n switcher: move upwards

### ISSUE THREAD

**Issue by andreslucena** [decidim/decidim.org#25]
I think it's better if it's on the same way as we do on decidim-design, having it on another bar.

**Comment by htmlboy** [comment]
<img width="1277" alt="screen shot 2017-10-05 at 15 54 17" src="https://user-images.githubusercontent.com/468685/31230893-a8632894-a9e5-11e7-9cd4-cf33795936b0.png">

This is quick mockup of the proposed result. Thoughts, @xabier @andreslucena ?

**Comment by xabier** [comment]
I like it!

**Comment by htmlboy** [comment]
Fixed in: https://github.com/decidim/decidim.org/pull/68
