### ISSUE TITLE
Error URL when switching back to english

### ISSUE THREAD

**Issue by Dynnammo** [decidim/decidim.org#269]
As a user, if I arrive on `decidim.org/fr/` for instance and I want to switch back to english, the URL displayed redirects me on the same language.

It is the case for every language on the plaform (apart from english)
![image](https://user-images.githubusercontent.com/33259633/143082740-8674c391-6dc4-4aea-bdd4-0e196c060461.png)

**Comment by andreslucena** [comment]
Thanks for the report, I can confirm it in production
