### ISSUE TITLE
Implement new design

### ISSUE THREAD

**Issue by furilo** [decidim/decidim.org#281]
- Prototip web: https://www.figma.com/proto/9KP8rBo6G1vLAqnve6PD2v/Decidim---Gr%C3%A0fica?page-id=0%3A1&node-id=420%3A61955&viewport=241%2C48%2C0.05&scaling=min-zoom&starting-point-node-id=420%3A61955&show-proto-sidebar=1
- Prototip mòbil (no està enllaçat, però podeu navegar-lo amb les fletxes del teclat): https://www.figma.com/proto/9KP8rBo6G1vLAqnve6PD2v/Decidim---Gr%C3%A0fica?page-id=250%3A18058&node-id=420%3A59373&viewport=241%2C48%2C0.11&scaling=min-zoom&starting-point-node-id=420%3A59373

- Disseny web (desktop): https://www.figma.com/file/9KP8rBo6G1vLAqnve6PD2v/?node-id=0%3A1
- Disseny web (mobile): https://www.figma.com/file/9KP8rBo6G1vLAqnve6PD2v/?node-id=250%3A18058

**Comment by Crashillo** [comment]
Does it worth removing Foundation also from this project?

**Comment by furilo** [comment]
@andreslucena ok to use Tailwwind here?

**Comment by andreslucena** [comment]
>  @andreslucena ok to use Tailwwind here?

Yes, of course. I thought that I've mentioned in the meeting last week, but I think this is a great place to try it.

**Comment by furilo** [comment]
Perfect, thanks

**Comment by Crashillo** [comment]
The following FAQs snippet, should it be an accordion or just simple redirections (onclick) to the /faqs website? cc/ @andreslucena 

![image](https://user-images.githubusercontent.com/817526/159976641-aa16f4c6-5266-40c7-bd19-f960a7251f58.png)

**Comment by andreslucena** [comment]
Talked with @carolromero, and we thought accordion would be the best

**Comment by Crashillo** [comment]
@decidim/product I dunno where the following links point:

1. In `/get-started` page, both buttons, currently pointing to: `/community` and `try.decidim.org/`, respectively
![image](https://user-images.githubusercontent.com/817526/161742788-90e9f93f-eec6-4756-8f25-d14186d3e2e7.png)

2. This widget reads `data/testimonials.yml`. It misses both the picture and the _read the case study_ link. Found in `/get-started` and `/usedby` pages
![image](https://user-images.githubusercontent.com/817526/161744863-87b1f558-7b06-45b6-ac5d-a1b51709e6c0.png)

3. In `/services` page, all _Get in touch_ links are missing. Setup at `data/services.yml`
![image](https://user-images.githubusercontent.com/817526/161745105-cbf10f25-5506-496b-af67-e276733f6e26.png)

4. In `/about` page, the CTA _Our assembly_
![image](https://user-images.githubusercontent.com/817526/161746273-dcbb95fb-00b2-4f60-8a2a-06d19c953d73.png)

5. In `/press` page, _Press kit_ section reads `data/press.yml`, it misses community photos.
![image](https://user-images.githubusercontent.com/817526/161746772-a8946a31-0e25-4c8c-95d6-0a386877f4f4.png)

6. Similar to hte previous one, `Social media` section reads `data/links.yml`. Let me know if some networks are missing
![image](https://user-images.githubusercontent.com/817526/161747126-412195d0-8765-42c0-a616-9d28479856b2.png)

7. The footer content setup is located in `data/links.yml`. Rearrange the links as you wish
![image](https://user-images.githubusercontent.com/817526/161747942-23b26885-f764-4dde-b075-b22e616cc5f9.png)

If you see something else missing, please report it. Once deployed, I'll share the url in the PR.

**Comment by andreslucena** [comment]
@Crashillo thanks for your amazing work. We've been working on the last few months on this with @carolromero, and yesterday we've uploaded it in production. Now it's available at https://decidim.org

I'm closing this issue as this is already done.
