### ISSUE TITLE
Add Press to admin Netlify CMS

### ISSUE THREAD

**Issue by carolromero** [decidim/decidim.org#335]
In order to quickly add Media highlights on the [Press](https://decidim.org/press/) page, we'd need a form in Netlify CMS with the following fields:
* Title
* Link
* Media outlet
![image](https://user-images.githubusercontent.com/23509895/222677851-49fb188e-79db-4043-9829-368fc1447a48.png)

**Comment by andreslucena** [comment]
This is already implemented and available at https://decidim.org/admin 

I didn't do it with PRs as Netlify CMS doesn't play nice with using a PR, as we would need to be changing the configuration to work in a branch and it's too much hassle just a for a quick change. 

Closing this issue as it's already done.
