### ISSUE TITLE
Change LICENCES to AfferoGPLv3

### ISSUE THREAD

**Issue by xabier** [decidim/decidim.org#39]
Change LICENCES to AfferoGPLv3

**Comment by andreslucena** [comment]
Are you talking about this repository of decidim.org? If so, we can't change it, it's based on another project that had the MIT license.

**Comment by andreslucena** [comment]
It looks like it could be done without removing the MIT: https://softwareengineering.stackexchange.com/questions/105912/can-you-change-code-distributed-under-the-mit-license-and-re-distribute-it-unde

**Comment by xabier** [comment]
You simply have to point to the original bits as MIT licensed and the rest + original as GPL. This should translate as simply putting the whole project under GPL license and (I think this is optional) a link to the original part with MIT.

**Comment by xabier** [comment]
#54 PR solves this issue
