### ISSUE TITLE
Add new organizations in Cooperating entities section on main page

### ISSUE THREAD

**Issue by xabier** [decidim/decidim.org#41]
* [ASPgems](https://aspgems.com/)

**Comment by andreslucena** [comment]
Logo: 
![image](https://user-images.githubusercontent.com/717367/31166427-053b0764-a8ef-11e7-87fd-53d68bd8cee5.png)

**Comment by xabier** [comment]
We should also consider including Open Source Politics for their implication and promotion of the project
