### ISSUE TITLE
Update main page with assemblies

### ISSUE THREAD

**Issue by xabier** [decidim/decidim.org#44]
Right now the front page focuses on participatory processes. We need to update it to reveal a core feature of the platform: Assemblies.

We can either create a new box for the first or section of three, or substitute one.

* **Title**: 
   * EN: Create and Manage Assemblies, Committees and Participatory Organs
   * ES: Crea y Gestiona Asambleas, Comités y Órganos de Participación
   * CA: Crea i Gestiona Assemblees, Comitès i Òrgans de Participació
* **Content**: 
   * EN: You can easily create a site for any kind of working group, assembly, committee or participatory organ, to help people join their meetings, support their proposals, follow their minutes or audit their activities.
   * ES: Crea fácilmente cualquier tipo de grupo de trabajo, asamblea, comité o órgano participativo, para que la gente pueda acudir a las reuniones, apoyar sus propuestas, seguir sus actas o auditar sus actividades.
   * CA:  Crea fàcilment qualsevol tipus de grup de treball, assemblea, comitè o òrgan participatiu, perquè la gent pugui acudir a les reunions, donar suport a les seves propostes, seguir els seus actes o auditar les seves activitats.
* **Image**: 
![image](https://user-images.githubusercontent.com/537284/31620089-9fc2e38c-b296-11e7-8415-07b5e34d8714.png)

**Comment by htmlboy** [comment]
Related to #45 . If we have 3 new blocks we might as well create a new highlighted features block, but it still doable with 2.

**Comment by xabier** [comment]
We can add one more if needed! We have plenty of features to highlight

**Comment by htmlboy** [comment]
This is solved in https://github.com/decidim/decidim.org/tree/features-3rd-block

Before merging, we need proper content and images:
- Content for the 3rd feature (currently dummy text)
- Images for the Initiatives feature and the 3rd feature
- Review of translations

If you change the images names, please notice that each image is linked twice in the HTML to make mobile/desktop views simpler.

This issue is shared with #45

**Comment by xabier** [comment]
@htmlboy this issue has been updated with your requirements.

**Comment by htmlboy** [comment]
Fixed in: https://github.com/decidim/decidim.org/pull/71
