### ISSUE TITLE
Update main page with Iniciatives

### ISSUE THREAD

**Issue by xabier** [decidim/decidim.org#45]
Right now the front page focuses on participatory processes. We need to update it to reveal a core feature of the platform: Iniciatives.

We can either create a new box for the first or section of three, or substitute one.

* **Title**: 
   * EN: Let people's initiatives reach their goal
   * ES: Permite que las iniciativas ciudadanas alcancen su objetivo
   * CA: Permet que les iniciatives de la gent aconsegueixin el seu objectiu
* **Content**: 
   * EN: Decidim makes possible for people to create, manage and push their initiatives (e.g. to open a proposal, create a new participatory process, promote a consultation) to reach their goal. It is possible to define types of initiative, specifying the number of signatures or supports they need to achieve, and participants get access to collect support and bring their initiative to power.
   * ES: Decidim permite a la gente crear, gestionar e impulsar sus propias iniciativas (p.e. crear una asamblea, crear un proceso de participación, promover una consulta, etc.) y alcanzar su objetivo. Es posible definir diferentes tipos de iniciativas, asignándoles un número mínimo de firmas o apoyos requeridos, y las personas participantes pueden iniciarlas, recabar apoyos e impulsar su iniciativa a gobierno.
   * CA: Decidim permet a la gent crear, gestionar i impulsar les seves pròpies iniciatives (p.e. crear una assemblea, crear un procés de participació, promoure una consulta, etc.) i aconseguir el seu objectiu. És possible definir diferents tipus d'iniciatives, assignant-los un nombre mínim de signatures o suports requerits, i les persones participants poden iniciar-les, recollir suports i impulsar la seva iniciativa a govern. **REVIEW DONE**
* **Image**: 

![image](https://user-images.githubusercontent.com/537284/31620748-5f74d7de-b298-11e7-80a0-f98386f1fe51.png)

**Comment by htmlboy** [comment]
Adding a 4th block would make the design unbalanced. I think a substitution is better. Please let me know when you have a snapshot and which one do you want to change.

**Comment by xabier** [comment]
If we are to remove a block it would be the last one, because generally users don't care too much about modularity and scalability of the sofware.

**Comment by htmlboy** [comment]
This is solved in https://github.com/decidim/decidim.org/tree/features-3rd-block

Before merging, we need proper content and images:
- Content for the 3rd feature (currently dummy text)
- Images for the Initiatives feature and the 3rd feature
- Review of translations

If you change the images names, please notice that each image is linked twice in the HTML to make mobile/desktop views simpler.

This issue is shared with #44

**Comment by xabier** [comment]
@htmlboy I have updated the issue with an image and 3 language text. @carolromero @arnaumonty if you can double check the Catalan translation that would help :smile:

**Comment by carolromero** [comment]
@xabier translation checked, found just a little typo 😉

**Comment by htmlboy** [comment]
Fixed in: https://github.com/decidim/decidim.org/pull/71
