### ISSUE TITLE
Review CSS / headings sizes on /blog

### ISSUE THREAD

**Issue by andreslucena** [decidim/decidim.org#50]
The heading sizes doesn't look well: 

![image](https://user-images.githubusercontent.com/717367/31226316-f4cb5f40-a9d5-11e7-9cd3-55572b28bbe9.png)

https://decidim.org/blog/

**Comment by htmlboy** [comment]
The h1 should disappear from the markdown body, we're using the metadata title instead to avoid multiple h1 in the summaries view. Also, I'd recommend to match the post name with the title.

**Comment by andreslucena** [comment]
Ok, closing this issue.
