### ISSUE TITLE
Remove notices from JAM 

### ISSUE THREAD

**Issue by andreslucena** [decidim/decidim.org#79]
JAM already passed, we should remove the alerts/notices

**Comment by xabier** [comment]
Maybe we can leave it for a month or so, the content of the JAM is relevant and the videos of the talks and the presentation slides will be uploaded soon. I also had the impresion we should remove it but after a second thought I saw it convenient to maintain it.

**Comment by andreslucena** [comment]
:+1: related with #81 #82 #83
